---
- hosts: kubes
  remote_user: chase
  become: yes

  tasks:
    - name: update
      apt:
        update_cache: yes

    - name: install some certs
      apt:
        name: apt-transport-https
        state: installed

    - name: add Kubernetes repo key
      apt_key:
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

    - name: add Kubernetes repo
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        update_cache: yes

    - name: install docker
      apt:
        name: docker.io
        state: latest

    - name: install Kubernetes
      apt: name={{ item }} state=latest
      with_items:
        - kubelet
        - kubeadm
        - kubectl
        - kubernetes-cni
